# start with: dc run --rm magicmirror
version: '3'

services:
  magicmirror:
    container_name: mm
    image: registry.gitlab.com/khassel/magicmirror:develop_debug
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command:
      - /bin/bash
      - -c
      - |
        # comment out if needed:
        #rm -rf ./*
        #rm -rf ./.*
        #git clone -b develop https://github.com/khassel/MagicMirror.git .
        #npm install
        #mv config/config.js.sample config/config.js
        #sed -i 's|address:.*|address: "0.0.0.0",|g;s|ipWhitelist:.*|ipWhitelist: [],|g' config/config.js
        #touch css/custom.css
        Xvfb :99 -screen 0 1024x768x16 &
        export DISPLAY=:99
        /bin/bash
